### ISSUE TITLE
Module is currently non-functional with foundry v10.285

### ISSUE THREAD

**Issue by Seanamal** [MarkPearce/footsteps-of-otari#3]
Module no longer works with current version of foundry.

**Comment by MarkPearce** [comment]
Thanks for the heads up. Not unexpected…I’m in no hurry to upgrade myself. But  I’ll take a look at in the coming weeks.  maybe this weekend. 

The journals and such should be unaffected?

**Comment by Seanamal** [comment]
V10 made significant changes to the journal system so there may be bugs there too.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Seanamal** [comment]
BTW, great module! The visual effects add some real nice storytelling.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MarkPearce** [comment]
new version published for 10
