### ISSUE TITLE
User support request, foundry v10.291

### ISSUE THREAD

**Issue by tatsumasagc** [MarkPearce/footsteps-of-otari#4]
I have added the macro to my macro bar and opened the Footsteps Control.
I am using the Premium Module for Abomination Vaults and have tried both the Classic Option and the Remaster option.
I've selected the correct level (in this case Two) neither the "play" button nor the "Create Ghost" appear to do anything

**Comment by MarkPearce** [comment]
that's curious. Can you confirm the module is active?
Do you have any console error messages?

**Comment by MarkPearce** [comment]
Oh i see the problem. This is the version 9 repo.  You may have the old version installed.  

Update the module, or delete and re-install.
