### ISSUE TITLE
Remaster?

### ISSUE THREAD

**Issue by ksignorini** [MarkPearce/footsteps-of-otari#8]
I see a choice for selecting Class or Remaster of the module.

Is there really a Remaster of the AV module? Or is this a future option?

**Comment by MarkPearce** [comment]
Classic refers to the original 3 book set, remaster is the reissue
compilation.

This was before Paizo released an ‘remaster’ rules set

**Comment by ksignorini** [comment]
I understand the difference in rules. I just wasn't sure why there was a "Remaster" option when the Ab Vault module doesn't (to my knowledge) have a Remaster version. Did you have the option in your module for some reason? Is that option coming out (in light of your comment above)?

**Comment by MarkPearce** [comment]
No there isn’t.


Remaster in the module reveres the the anthology release of AV.
